### PR TITLE
Add Bitcoin Private Support

### PR DESCRIPTION
**Pull request by sulmone**
I have tested signing and broadcasting transactions from a custom build of electrum-btcp with success. Please advise concerning adding to the chrome webapp vs. adding to the new desktop app in development.

Thanks!

### CODE REVIEW

**Comment by sulmone** [comment]
To add ledger blue support - is it as simple as adding the corresponding app / icon files?
Additionally, can you point me to the color pallette requirements?

Thanks!

**Comment by fdv** [comment]
Hello.

Do you have your own wallet / infrastructure to use the Nano S application? As we are rewriting our Desktop wallet from scratch, we won't be able to add a new coin, and don't plan to add a new infrastructure for BTCP yet.

**Comment by sulmone** [comment]
Yes, we have an electrum wallet that supports ledger transactions.

I have the changes for ledger support on a branch here: https://github.com/BTCPrivate/electrum-btcp/tree/feature/hw_wallet

Let me know what else is needed - we can also set up claiming from BTC on the same electrum wallet.

**Comment by btchip** [comment]
Done in the upcoming version, so closing.

**Pull request closed without merging**
