### PR TITLE
Added Syscoin to Makefile

### PR DESCRIPTION
**Pull request by sschepis**
Added support for Syscoin to the Makefile

### CODE REVIEW

**Comment by sidhujag** [comment]
I've completed the ledger chrome wallet PR here which should be reviewed in conjunction with this PR:
https://github.com/LedgerHQ/ledger-wallet-chrome/pull/106

**Comment by sidhujag** [comment]
I've completed the ledger wallet webtool PR here which should be reviewed in conjunction with this PR: https://github.com/LedgerHQ/ledger-wallet-webtool/pull/26

**Comment by btchip** [comment]
Pending our Ledger Live and backend reorganization. Can be prioritized if you're operating your own wallet.

**Comment by sidhujag** [comment]
@btchip sorry can you elaborate on the "operating your own wallet part"? Is there any documentation about this.

**Comment by sschepis** [comment]
@btchip please elaborate on what you mean here by "operating your own wallet"

**Pull request closed without merging**
