### PR TITLE
Add Hydra coin support

### PR DESCRIPTION
**Pull request by ablagoev**
Hydra is an open-source Proof-of-Stake blockchain with a unique set of economic features.
It packs a unique combination of inflationary as well as deflationary mechanics as part
of its economy that work in parallel and let the real adoption define its total supply.

https://hydrachain.org/

### CODE REVIEW

**Comment by TamtamHero** [comment]
In the Makefile, COIN_KIND should be a new one, COIN_KIND_HYDRA
COIN_KIND_HYDRA should be declared in `include/btchip_context.h` next to every other kinds
And then, as you expect the app to behave just like it would for Qtum, you should spot all the places where COIN_KIND_QTUM is used in the app and add a logical OR for COIN_KIND_HYDRA.

**Comment by ablagoev** [comment]
Hello,

Thank you for all the feedback. I have amended the original commit and have defined a separate COIN_KIND for Hyda.

Let me know if anything else is needed.

Best,
Alex

**Comment by TamtamHero** [comment]
Also, one last thing: you should add hydra to the listvariants lines here: https://github.com/LedgerHQ/app-bitcoin/blob/master/Makefile#L312-L317
Same on this line: https://github.com/LedgerHQ/app-bitcoin/blob/master/Makefile#L187

**Comment by ablagoev** [comment]
Hey,

Sorry about that, added the coin type to the variants and unsupported error cases.

Best,
Alex

**Pull request merged**
