### PR TITLE
Added NavCoin Support

### PR DESCRIPTION
**Pull request by mxaddict**
Added NavCoin Support

Added the images required and the base changes required in Makefile

Will be creating additional PR's for ledger-live-desktop once done with integration.

### CODE REVIEW

**Comment by mxaddict** [comment]
Website: https://navcoin.org/en

COIN_P2PKH_VERSION=53
https://github.com/navcoin/navcoin-core/blob/926c49a273189277afad6a3fa9f91be060682b3c/src/chainparams.cpp#L216

COIN_P2SH_VERSION=85
https://github.com/navcoin/navcoin-core/blob/926c49a273189277afad6a3fa9f91be060682b3c/src/chainparams.cpp#L218

**Comment by mxaddict** [comment]
@TamtamHero  @btchip What else is required to get this bolos app integration added to the "dev apps" in ledger-live app?

**Review by proletesseract — COMMENTED** [review]
utACK code looks correct.

**Review by proletesseract — APPROVED** [review]

**Comment by mxaddict** [comment]
@gre this is the PR i meant.

**Pull request closed without merging**
