### PR TITLE
Add Feathercoin

### PR DESCRIPTION
**Pull request by maschwanden**
Add Feathercoin support for Ledger Nano S and Ledger Blue.

### CODE REVIEW

**Comment by Icreatedthisaccountjustforonereason** [comment]
Please add Feathercoin to Ledger Nano S and Ledger Blue

**Comment by x0n4r** [comment]
Dear Support, please add Feathercoin to Ledger Nano S and Ledger Blue. Regards

**Comment by stefantastico** [comment]
Pls. add **Feathercoin** support for Ledger Nano S and Ledger Blue.

**Comment by DongwonTTuna** [comment]
please !!

**Comment by alexw3f** [comment]
go for it! 👍

**Comment by javadth** [comment]
hi

please add FTC to Ledger Nano

**Comment by btchip** [comment]
Pending our Ledger Live and backend reorganization. Can be prioritized if you're operating your own wallet.

**Comment by jpenunur** [comment]
Hi, please add Feathercoin to Ledger Nano

**Comment by Sapp11** [comment]
Hello Ledger support, can you pls add Feathercoin to Ledger Nano S and Ledger Blue..

**Comment by lclc** [comment]
If I can help speeding this up please let me know (here or lucas.betschart@feathercoin.foundation).

**Pull request closed without merging**
