### PR TITLE
Added support for Zclassic (ZCL)

### PR DESCRIPTION
**Pull request by interbiznw**
This adds support for Zclassic ( ZCL ) & added Zclassic Icons

https:/www.zclassic.org
https://github.com/z-classic/zclassic

### CODE REVIEW

**Comment by sandeepnailwal** [comment]
Desperately need zclassic support before the BTCP fork.

**Comment by petlap** [comment]
Ledger add ZCL before the fork please, this is gonna be huge

**Comment by aurelius2001** [comment]
Please please add support for BTCP fork....asap! thank you

**Comment by LordZive** [comment]
Hi Ledger, It would be great if you add support for BTCP fork :-)

**Comment by wznoinski** [comment]
@btchip LedgerHQ do you need some users to build it to speed up the pull?

**Comment by douglasdeodato** [comment]
when the wallet will be available for the users? thank you

**Comment by fdv** [comment]
Hi @interbiznw 

Can you fix the conflicts in your PR before we can review it please?

**Comment by interbiznw** [comment]
Will take a look at it and fix @fdv thanks!

**Pull request closed without merging**
