### PR TITLE
add XVG support

### PR DESCRIPTION
**Pull request by justinvforvendetta**

### CODE REVIEW

**Comment by btchip** [comment]
Thanks for the PR. I'm a bit confused as this doesn't include any privacy specific change or address format. Do you confirm that it's possible to transact fully with only this PR and no additional changes ?

**Comment by justinvforvendetta** [comment]
@btchip when you say address format, are you implying stealth addressing?

**Comment by btchip** [comment]
yes, or anything else specific to XVG

**Comment by justinvforvendetta** [comment]
@btchip i think adding xvg stealth addr wouldn't be much help, since no exchanges seem to support stealth withdraw, and most incoming coins to ledger would be from an exchange. although, i am curious, can ledger broadcast tx out thru tor?

**Comment by HDsign** [comment]
@btchip any progress on this? 
Do you need help with something or more answers?

Anyway an update on the progress would be much obliged 👍

**Comment by MynxGithub** [comment]
@btchip any progress on this?
Do you need help with something or more answers?

Anyway an update on the progress would be much obliged +1

**Comment by btchip** [comment]
We're waiting for additional technical assessment on whether the minimum feature set provided in this PR is enough to support XVG or not - as we don't want to merge this then have to implement the missing features on our own

**Comment by marpme** [comment]
@btchip hey btchip, I'm Marvin one of the core member (developer) from verge and I wanted to quickly ask if there's a documentation for testing those kinds of applications on an actual device.

I've found the following documentation (https://ledger.readthedocs.io/en/latest/) about the device and how to install the app onto my ledger nano s, but I also wanted to make sure that address generation and the signing of transactions work properly before giving the "go". 

I'm currently at the point, where I have the verge app compiled and loaded onto my nano device, but how can I actually interact with it? Is there a simple python script to test the address generation and the signing of one transaction?

**Comment by vishal3967** [comment]
No point providing an integration without stealth addresses added.

**Comment by marpme** [comment]
@btchip 

**Update on this one:** I found a  way to Integrate the self-built ledger app into our wallet and checked out quite some things and everything seem to work out very well. The only thing that is not working correctly, is the icon for the nanoS. Maybe you can have a look there, as the icon is not displayed correctly, although the resolution and the icon placement looks correct. 

Thank you for your support!

**Comment by justinvforvendetta** [comment]
@vishal3967 can you explain why?

**Comment by vishal3967** [comment]
@justinvforvendetta- because as an optional "privacy" coin, you guys literally only have stealth addresses and some weird Tor integration. And now you want to include Verge on ledger without them? Seems like half-assed/incompetent work to me.

**Comment by justinvforvendetta** [comment]
@vishal3967 what do you mean by "weird tor integration"?

**Comment by vishal3967** [comment]
@justinvforvendetta not sure why you conveniently ignored my answer to your question and are now asking another question? Also, are you guys just waiting for Particl to implement what you said you'd deliver so you can just copy it?

**Comment by 2lazy2debug** [comment]
@vishal3967 given the fact that your only repo it’s some sort of web page that writes “Luke, I’m your father”, I think you don’t have the necessary competence to understand the complexity of the technologies behind Verge.

Jokes aside, If you have any feedback to submit, a question or a constructive feedback, feel free to reach us anywhere else than a Pull Request, it’s just polluting for us and the guys on Ledger side. You can also write us an email here : contact@vergecurrency.com. 

P.s.: in the original script of Star Wars, Darth Vader answered to Luke by saying “No, I am your father”, he never said “Luke”

**Comment by vishal3967** [comment]
@carbasm this account was created to do an online course, why would it have a bunch of repos I contributed to? And instead of answering my question about stealth addresses (this is part of the ledger integration, so no there's no "polluting" going on), you try to attack me as a person. Goes to show you don't have answers for my questions. Quite similar to how Justin Valo dodged my reply too. If you think you're so competent with Verge tech, can you explain how RingCT can be added with an optionally coin where a majority of transactions are not private? Where would you get the transactions for the ring mix-ins?

**Comment by 2lazy2debug** [comment]
@vishal3967
Sorry if you felt personally attacked, there was no intention (even if you typo’ed my username).

Please join our discord or Telegram servers if you want to discuss this, we will be happy to answer, or use mail given before. No one’s dodging you, we just want to keep communication with Ledger clean. Thus, I’ll delete my comments later to clean up. 

Kind Regards,

Manuel

**Comment by justinvforvendetta** [comment]
@vishal3967 what do you mean? ringct will be using recent inputs from the past 24 hours, as in most cases that it's used. I guess you'll have to wait and see, Luke.

-Dad

**Comment by Flenst** [comment]
Beside optional stealth addressing being unsecure and traceable an integration without them implemented would break Ledger support whenever you come to the conclusion to make stealth addressing mandatory.

Addition of stealth addressing and possible RingCT in the future is a lot of work you will not do when it is integrated without it. Furthermore would it be misleading people in wrong safety regarding their privacy, although your Ledger support approach only allows COMPLETELY public transactions on the blockchain.

If we take ZCash as an example and their implementation they also don't support their privacy solution. But here the Ledger doesn't support it because of hardware requirements. At Verge it is not the hardware, it is just Verge not wanting to develop the full integration because the devs know this would be A LOT of work.

For me as a privacy supporter a "privacy coin" integration without ANY privacy feature regarding the blockchain is simply dangerous and misleading. Especially if the devs just don't want to develop a solution or are not capable of doing it.

**Comment by vishal3967** [comment]
@Flenst do you think they don't know this? They already know all of this and have even been told multiple times. They just don't care. They'd rather do half-assed work than not do anything cause "hurr durr Ledger support". I'm pretty sure they're just going to wait for some other coin to implement it right and then copy it.

**Comment by vishal3967** [comment]
@justinvforvendetta you cannot use known inputs. And we both know most of the inputs are known because stealth addresses are not compulsory. RingCT does not work with optional privacy.

**Comment by Flenst** [comment]
@vishal3967  copying would be ok, but an integration without stealth addressing is dangerous. If there is nothing to copy currently this shouldn't be Ledgers problem.

**Comment by justinvforvendetta** [comment]
@vishal3967 stealth transactions and regular public key txs are the same thing aside from address structure. btw you dont work at ledger or verge, nor are you a dev so why are you here again?

**Comment by Kryptoxic** [comment]
Any updates on this? Would be great if there was a precompiled app to sideload and test on my own Nano S.

**Comment by marpme** [comment]
@gre @btchip Reviewed all stuff internally and tested all basic functionalities by utilizing `ledgerjs/btc-app`. Rebased to latest master.

**Comment by justinvforvendetta** [comment]
@btchip this is up to date and functioning properly =]

**Comment by bfreshhb** [comment]
Any updates? I'd love to add $XVG to my ledger 😁 @btchip

**Comment by flmuel** [comment]
@btchip Please have another look :)

**Comment by TheNite** [comment]
why is this still not added to ledger??

**Pull request closed without merging**
