### PR TITLE
Added Bitcore BTX Support

### PR DESCRIPTION
**Pull request by dArkjON**
This code adds support for BTX Bitcore : https://bitcore.cc
Github Page : https://github.com/LIMXTEC/BitCore

Include :
+ Bitcore icons
+ Bitcore Code

This Pull Request is for adding Bitcore BTX Coin to the Ledger for a normal storage.

Bitcore is a Hybrid Fork from the Bitcoin Blockchain on Block : #492820
If there a possible solution to give Bitcon Holder Access to this coins whould be a nice feature !.

### CODE REVIEW

**Review by btchip — CHANGES_REQUESTED** [review]
Change to specific P2PKH/P2SH versions and add replay protection - if not possible we'll try to support through an upcoming fork claiming tool, but won't offer a wallet for it.

**Comment by dArkjON** [comment]
Hey Guys,
Bitcore is the only fork working as a hybrid fork, this technic is the biggest replay protection itself.
The Coin have a own Genesis Block and also started with a new Blockchain on Block 0/1.

On Bitcoin Block : 492820 was a Snapshot and we load every Wallet with 50% BTX from the BTC Balance. The BTX are availible on the same Key Pair just another Network and replay protected because there are no BTC TXID exist in the BTX Blockchain and otherwhise.

Insight : https://insight.bitcore.cc/
Explorer : https://chainz.cryptoid.info/btx/

If there any infos, details or help we can provide please lets us know about it.

**Comment by dArkjON** [comment]
@btchip @fdv 
If there any infos, details or help we can provide please lets us know about it.

**Review by dArkjON — COMMENTED** [review]
The Coin have a own Genesis Block and also started with a new Blockchain on Block 0/1.

**Comment by dArkjON** [comment]
@fdv @btchip 
Please give us a respond to this topic. Bitcore is registered coin types for BIP-0044 : 0x800000a0

**Comment by dArkjON** [comment]
New Pull #72

**Pull request closed without merging**
