### PR TITLE
Add Denarius (D)

### PR DESCRIPTION
**Pull request by metaspartan**
Added Denarius (DNR) support including icons.

This adds support for Denarius (DNR)
https://denarius.io
https://denarius.pro
https://blockforums.org
http://github.com/carsenk/denarius

Other PR is here: https://github.com/LedgerHQ/ledger-wallet-chrome/pull/91

### CODE REVIEW

**Comment by metaspartan** [comment]
Any update on this @btchip or @fdv :smile:

**Comment by metaspartan** [comment]
Can we get this reviewed yet? Any ETA or updates in regards to adding Denarius?

**Comment by metaspartan** [comment]
Any update on this review @btchip or @fdv ?

**Comment by buzzkillb** [comment]
I thought Ledger was going to help out coins that could get commits ready to rock and roll?

**Comment by radar24** [comment]
I can't wait for dnr support on ledger wallet!

**Comment by enkayz** [comment]
If there is anything that needs to be addressed please let us know and we will organize it.

**Comment by btchip** [comment]
Nothing special there - pending our Ledger Live and backend reorganization. The device application itself is fine. Can be prioritized if you're operating your own wallet.

**Review by btchip — DISMISSED** [review]

**Comment by JohnPain** [comment]
@btchip Denarius has its own wallet for a long time now. Windows, Linux and Mac. Check denarius.io for downloads - or here on github. Looking forward to implementation

**Comment by metaspartan** [comment]
Updated Denarius (D) for merge

**Comment by metaspartan** [comment]
6 years and just closed? lol

**Pull request closed without merging**
