### PR TITLE
Add Monacoin support.

### PR DESCRIPTION
**Pull request by cryptcoin-junkey**
Monacoin is the famous coin in Japan.

Details:
Tether: https://monacoin.org/
Github: https://github.com/monacoinproject/monacoin
Bitcointalk: https://bitcointalk.org/index.php?topic=392436.0
Marketcap: https://coinmarketcap.com/currencies/monacoin/

This will work fine even though the patch is not tested yet. Because code of Monacoin is from Litecoin.

### CODE REVIEW

**Comment by dvcrn** [comment]
Anyhow we can help to get Monacoin support through? As @cryptcoin-junkey said, MONA is the most famous coin in Japan, currently trading at higher prices than a lot of other coins out there. Would love to see support for it in my Nano S

**Comment by cryptcoin-junkey** [comment]
An additional information.
Some Monacoin users have ported released Monacoin version of Electrum / Electcumx.
https://electrum-mona.org/

So they don't need official desktop/web apps by Ledger. Just need blue-app support.

**Comment by k06a** [comment]
:+1:

**Comment by cedricwalter** [comment]
would love to also have Monacoin support 👍

**Comment by tfe2012** [comment]
+1 for monacoin

**Comment by luiscarrasco** [comment]
Merge Merge Merge!

**Comment by terry90** [comment]
Merge ?

**Comment by tfe2012** [comment]
Yes

**Comment by MissMonacoin** [comment]
I heard Ledger support Monacoin. Is it true?

**Comment by cryptcoin-junkey** [comment]
Updated to the current master branch.

**Comment by fdv** [comment]
Hello @cryptcoin-junkey 

Can you please rebase to the last master branch so we can review it please? 

Thank you very much

**Comment by cryptcoin-junkey** [comment]
@fdv Okay I rebased it. Could you review this? Thanks!

**Comment by wakiyamap** [comment]
when ?

**Comment by cryptcoin-junkey** [comment]
I resolved conflicts and force pushed to here.

**Comment by lodotek** [comment]
Wow, 5 years since this was opened and still not merged in?

**Pull request closed without merging**
