### PR TITLE
Add ZClassic Coin

### PR DESCRIPTION
**Pull request by ghost**
As per requirements "Bolos app Release Candidate source code" 

Adding ZClassic coin to Makefile and Context. Tested against electrum-zcl 1.0.6

### CODE REVIEW

**Comment by douglasdeodato** [comment]
hi @theapplicationist  with which desktop wallet I can use the ZCL ledger app? electrum? sorry I could not find the answer, I want to do some tests too, thanks.

edit: this was commited few days ago, I might have to wait for the Next release right?

**Comment by ghost** [comment]
@douglasdeodato As per your edit, yes, this is not released yet. I'm not sure when that will happen but when it does it will be accompanied with a user guide with links etc! Hope that helps!

**Comment by douglasdeodato** [comment]
cheers mate.

**Comment by nimbosa** [comment]
[ZCL Electrum version 1.0.6](https://github.com/z-classic/electrum-zcl/releases/tag/Z!1.0.6) Release Candidate has been around since 2018 September 20, it should have been changed to "official release" immediately after that, sorry it was at "pre-release" label

BTW 1.0.7 is brewing (based on Electrum 3.1.x) and will be released soon after thorough testing

v1.1 will start implementing shielded transactions (spending to/from Z addresses), Thanks everyone!

**Pull request merged**
