### PR TITLE
Add LBRY Credits (LBC) Support

### PR DESCRIPTION
**Pull request by tzarebczan**
Cleaned up the original PR located at https://github.com/LedgerHQ/ledger-app-btc/pull/47 with the correct parameters and all required images. 

LBRY is a Bitcoin Core fork. Chainparams can be confirmed here: https://github.com/lbryio/lbrycrd/blob/e90d7f54cede3c1c5bfc3590351054bdc5a99480/src/chainparams.cpp#L179

Please let me know if there's anything missing or incorrect!

### CODE REVIEW

**Comment by tzarebczan** [comment]
Spoke to the Ledger team on Slack and we'll be getting an end to end scenario setup as well as ai files for the icons.

**Comment by kauffj** [comment]
Hey @EricLarch, we bought 20 Ledgers as holiday gifts for everyone at @lbryio. We'd really like to put them to first-class use. Any chance merging this could get a priority bump?

**Comment by tzarebczan** [comment]
Hey @EricLarch  / Ledger Team - I've rebased this PR and made sure the hex files works with the current BTC app release. Also confirmed this works with our Electrum client clone to send/receive LBC.  I'll reach out to the team on Slack as well. 

You can find all the icons, including the AI files, and hex file here: https://drive.google.com/drive/u/0/folders/19C3pnJ40bVYxx8aN-kCJTC7zylbrzmCz (I'm not sure where the glyph files come from, and how they differ from the gifs in the main repo, but I left them as such from our original submission). 

We'll need your assistance to complete the follow-on work to make this all work from the Ledger Live app. I took a stab at the modifications in the past, but since there's no way to setup an explorer api, could not test it all the way through. The repos are: 
https://github.com/tzarebczan/ledger-live-common/tree/lbry 
https://github.com/tzarebczan/lib-ledger-core 
https://github.com/tzarebczan/ledger-live-desktop/tree/lbry 

Since we are a fork of Bitcoin Core, the backend communication API should be very similar. You can check our Electrum implementation here: https://github.com/tzarebczan/electrum

**Comment by tzarebczan** [comment]
Electrum client to test with: https://github.com/tzarebczan/electrum/releases/tag/0.1.0

**Comment by hcleonis** [comment]
1st PR that added support of LBRY coin to Ledger BTC app. PR content has been merged a long time ago, outside of github => PR can be closed.

**Pull request closed without merging**
